GET http://localhost:4000/api/users/
Content-Type: application/json


###
GET http://localhost:4000/api/users/14
Content-Type: application/json

###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "cedula": "1003402797",
    "nombre": "gustavo",
    "apellido": "garnau",
    "correo": "ggarnauarrieta@gmail.com",
    "telefono": "304000002",
    "ciudad": "monteria",
    "direccion": "calle 123",
    "password": "123456"
}
###
PUT http://localhost:4000/api/users/2
Content-Type: application/json

{
    "cedula": "1002202792",
    "nombre": "david",
    "apellido": "delgado",
    "correo":"daviddelgado@coso.com",
    "telefono":"300000004",
    "ciudad":"monteria",
    "direccion":"calle 123",
    "password":"123456"
}

###
DELETE http://localhost:4000/api/users/21
Content-Type: application/json

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "cedula": "20034",
    "nombre": "David",
    "apellido": "Delgado",
    "correo":"dmdr10jd225@gmail.com",
    "telefono":"3196846680",
    "ciudad":"monteria",
    "direccion":"calle 123",
    "password":"123456"
}
###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "correo":"dmdr10jd225@gmail.com",
    "password": "123456"
}
###
POST http://localhost:4000/api/login
Content-Type: application/json

{
    "correo":"ggarnauarrieta@gmail.com",
    "password": "123456"
}

###
GET http://localhost:4000/api/proveedores/
Content-Type: application/json

###
GET http://localhost:3000/api/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI4LCJjb3JyZW8iOiJkbWRyMTAyNUBnbWFpbC5jb20iLCJpYXQiOjE3MjA3OTc4MjgsImV4cCI6MTcyMDgwNTAyOH0.rdCSpKHaGE1flFWl2ZRupdy4Dq2SDLFVRpGnPpRIQT0
Content-Type: application/json


